apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - env:
        - name: POSTGRESQL_DATABASE
          value: boundary
        - name: POSTGRESQL_USER
          value: boundary
        - name: POSTGRESQL_PASSWORD
          value: boundary
        - name: POSTGRESQL_ADMIN_PASSWORD
          value: postgres
        - name: PGDATA
          value: /temp/data
        image: registry.redhat.io/rhel9/postgresql-15
        imagePullPolicy: Always
        name: postgres
        ports:
        - containerPort: 5432
          protocol: TCP
        # resources:
        #   limits:
        #     cpu: 60m
        #     memory: 512Mi
        #   requests:
        #     cpu: 30m
        #     memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  ports:
  - name: http
    port: 5432
    protocol: TCP
  selector:
    app: postgres
#  type: NodePort

