apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-admin
  namespace: boundary
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-admin
subjects:
- kind: ServiceAccount
  name: vault-admin
  namespace: boundary
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io